# This is a basic workflow to help you get started with Actions

name: Windows Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  msvc:
    name: ${{ matrix.name }} C++${{ matrix.cpp }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2016]
        cpp: [11, 14, 17]
        include:
          - os: windows-2019
            name: vs2019
          - os: windows-2016
            name: vs2017
    env:
      CPP_STANDARD: ${{ matrix.cpp }}
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cmake -DEVENTBUS_BUILD_TESTS:BOOL=ON . && cmake --build . --config Debug
      - name: run
        run: ctest -V -C Debug
