name: Ubuntu

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: ${{matrix.os}}
    name: ${{ matrix.name }} C++${{ matrix.cpp }}
    matrix:
      os: [ubuntu-latest, ubuntu-20.04]
      cpp: [17]
      version: [gcc7, gcc8, gcc9, clang]
    env:
      CPP_STANDARD: ${{ matrix.cpp }}
    steps:
    - uses: actions/checkout@v1
    
    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Debug -j4

    - name: Run tests
      run: |
        cd build
        ctest --build-config Debug
