name: Windows

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ develop ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.version }} C++${{ matrix.cpp }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [windows-latest]
        cpp: [17]
        version: [msvc, clangcl]
        include:
          - version: msvc
            generator: '"Visual Studio 17 2022"'
          - version: clangcl
            generator: '"Visual Studio 17 2022" -T "clangcl"'
    env:
      CPP_STANDARD: ${{ matrix.cpp }}
    steps:
    - uses: actions/checkout@v1
    
    - name: Configure
      run: cmake -G ${{ matrix.generator }} -S . -B build

    - name: Build
      run: cmake --build build --config Debug -j4

    - name: Run tests
      run: |
        cd build
        ctest --build-config Debug
